package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Sunday, May 4, 2025 6:51:11 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
  String to_upper (String str);
  String to_lower (String str);
  String capitalize (String str);
} // interface ReverseOperations
