package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Thursday, April 17, 2025 12:26:42 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
